#!/usr/bin/env python3

all:
	@echo "RPAL Interpreter"
	@echo "Usage: ./rpal.py <input_file> [-ast] [-st]"
	@echo "Options:"
	@echo "  -ast  Display the Abstract Syntax Tree and exit"
	@echo "  -st   Display the Standardized Tree and exit"

clean:
	find . -name "__pycache__" -type d -exec rm -rf {} +
	find . -name "*.pyc" -delete
